version: '3.8'

services:
  task-management-db:
    image: postgres:14-alpine
    container_name: task-management-db
    env_file:
      - ./backend/.env
    volumes:
      - ./volumes/task-management-db/data:/var/lib/postgresql/data:rw
    ports:
      - "5444:5432"
    stop_grace_period: 1m
  